// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivpykqxwwytffcwyiik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdnB5a3F4d3d5dGZmY3d5aWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDQzMjEsImV4cCI6MjA3MzYyMDMyMX0.EuwRd8ZLpvzYocRU04zzOhS3UNGGTMpef44DVKzR5Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});